### ISSUE TITLE
Table creation fails with DateTime Types

### ISSUE THREAD

**Issue by bullocp913** [ugexe/Perl6-Text--Table--Simple#6]
"Method 'chars' not found for invocant of class 'DateTime'" is the error thrown.

I found this because DBIish started to return DateTime Objects in the result set.

Thanks,
Pat

**Comment by ugexe** [comment]
You need to stringify your DateTime before passing it in. It would be impossible for a library to guess how to provide string functions for an arbitrary object.

**Comment by bullocp913** [comment]
Alright, I figured it out.

Thanks for the quick reply.
