### ISSUE TITLE
Cannot use type objects in columns and rows

### ISSUE THREAD

**Issue by CIAvash** [ugexe/Perl6-Text--Table--Simple#8]
I just noticed my module doesn't work with the latest version of Text::Table::Simple(v0.0.5).

It seems after commit 0697a0ebf592b56d356da4dc1949011da6e974c8, type objects and undefined things don't get converted to an empty string. The error rises from the use of method `lines` on type objects.

A simple example:
```perl6
use Text::Table::Simple
say lol2table([Str], ([Int],));
```

Is this new behavior intentional?

**Comment by ugexe** [comment]
No; I suppose `map({ ($_ // '').lines ... })` is needed in place of `map(*.lines ...)` / `map({ .lines[] ... })`
